name: Retest Command

on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  contents: read
  pull-requests: read

jobs:
  retest:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/retest')
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        uses: actions/github-script@v7
        with:
          script: |
            // Get the PR
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_request_number: context.issue.number
            });
            
            // Get all workflow runs for this PR's head SHA
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: pr.data.head.sha,
              status: 'completed'
            });
            
            // Re-run failed workflows
            for (const run of runs.data.workflow_runs) {
              if (run.conclusion === 'failure' || run.conclusion === 'cancelled') {
                console.log(`Re-running workflow: ${run.name} (${run.id})`);
                try {
                  await github.rest.actions.reRunWorkflow({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: run.id
                  });
                } catch (error) {
                  console.log(`Failed to re-run ${run.name}: ${error.message}`);
                }
              }
            }
            
            // Also trigger new runs by creating a new check suite
            try {
              await github.rest.checks.createSuite({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head_sha: pr.data.head.sha
              });
              console.log('Triggered new check suite');
            } catch (error) {
              console.log(`Failed to create check suite: ${error.message}`);
            }